version: '3.8'

services:
  opendota-mcp:
    build: .
    image: opendota-mcp-server:latest
    container_name: opendota-mcp-server
    restart: unless-stopped
    # Optional: uncomment if you have a .env file with custom configuration
    # env_file:
    #   - .env
    stdin_open: true  # Required for MCP stdio communication
    tty: true         # Required for MCP stdio communication
    # Optional: uncomment if you have a .env file
    # volumes:
    #   - ./.env:/app/.env:ro
    networks:
      - mcp-network
    # For potential future HTTP API support
    # ports:
    #   - "3000:3000"
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  mcp-network:
    driver: bridge